# Generated by Django 5.1.7 on 2025-03-11 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Waste Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('potential_uses', models.TextField(blank=True, null=True)),
                ('sustainability_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_types/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_types', to='waste_catalog.wastecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('RESEARCH', 'Research Paper'), ('GUIDE', 'Usage Guide'), ('REGULATION', 'Regulation Document'), ('CASE_STUDY', 'Case Study'), ('OTHER', 'Other')], max_length=20)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='waste_catalog.wastetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
