# Generated by Django 5.1.7 on 2025-03-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcedocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wastecategory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Waste Categories'},
        ),
        migrations.AlterModelOptions(
            name='wastetype',
            options={'ordering': ['-created_at']},
        ),
    ]
