# Generated by Django 5.1.7 on 2025-03-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastelisting',
            name='country',
            field=models.CharField(choices=[('TN', 'Tunisia'), ('LY', 'Libya'), ('DZ', 'Algeria')], default='TN', max_length=2),
        ),
    ]
