# Generated by Django 5.1.7 on 2025-03-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_wastelisting_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wastelisting',
            options={'ordering': ['-created_at']},
        ),
    ]
