# Generated by Django 5.0.6 on 2025-03-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_listingimage_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastelisting',
            name='currency',
            field=models.CharField(choices=[('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('DZD', 'Algerian Dinar')], default='TND', max_length=3),
        ),
    ]
