# Generated by Django 5.0.6 on 2025-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('TN', 'Tunisia'), ('LY', 'Libya'), ('DZ', 'Algeria')], max_length=2, null=True),
        ),
    ]
